// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Infrastructure.Database.Migrations;

[DbContext(typeof(TournamentContext))]
[Migration("20230504152552_Init")]
partial class Init
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.5")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Infrastructure.Database.Entities.TurnamentResult", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<decimal>("CurrentBalance")
                    .HasColumnType("decimal(18,2)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsWinner")
                    .HasColumnType("bit");

                b.Property<string>("PersonalNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("PrizeAmount")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("TurnamentResults");
            });
#pragma warning restore 612, 618
    }
}